### ISSUE TITLE
--span and --min-cumulative-frequency not exposed in MultiSampleGenotypeWithDuplexSequencing

### ISSUE THREAD

**Issue by bkohrn** [fulcrumgenomics/fgstr#34]
This is Brendan, working with Rosana on applications of the fgstr pipeline to her work with poly-G regions.  

We finally got a chance to download and test the new version from last week, and we noticed that the new options (--span and --min-cumulative-frequency) were only exposed in one pipeline (GenotypeFromGroupedBam), which is not the pipeline we usually use (MultiSampleGenotypeWithDuplexSequencing).  Would it be possible to expose these options in the MultiSampleGenotypeWithDuplexSequencing pipeline? 

Thank you for your efforts, 
Brendan

**Comment by nh13** [comment]
@bkohrn thanks for the report, all set!
